### ISSUE TITLE
a little suggestion 

### ISSUE THREAD

**Issue by ywhuofu** [MattFlower/organized#19]
Hey, thanks for wring this wonderful package. Would it be useful to embed more colors and symbols in the file to make it look better than org-mode? Here is a one example on sublime text https://github.com/aziz/PlainTasks 

But it's a simply to-do management tool. I felt there is so much more potential with orgnized.

**Comment by MattFlower** [comment]
Plain tasks looks pretty fantastic.  Thanks for the nice comment -- I spend some occasion free time on this because I use it every day and if it helps someone else, that's great!

One of the reasons to choose emacs org-mode as my source of truth is one of my big pet peeves -- I want my notes to be a plain text file.  When you start to render things like this, you lose this purity.  I've had problems with products like Evernote where the outline bullet points go wrong and you get two bullet points on the same line at different depths.  Blech!

One thing I do see in the distant future is the ability to have versions, one with the "raw" text and another with the "rendered" text.  This would be similar to what you see in a lot of markdown editors. 
 This would make underlining, bolding, links, etc a bit more polished.  Additionally, I would like to be able to export to html or pdf for those rare times when I need to project my notes in a meeting.  All those are features in the distant future though, for now, you're going to be stuck with text.

I'm going to close this issue for now.  I definitely hear what you are saying, and maybe this tool will be that one day.
