### ISSUE TITLE
Collapsing sections

### ISSUE THREAD

**Issue by shacker** [MattFlower/organized#21]
In emacs org-mode, Tab key cycles through open subtree, open all nodes in subtree, close.

I know tab is used for changing indentation levels in Organized. Will expand/collapse (which is SO useful) be added to Organized somehow?

**Comment by shacker** [comment]
Although I realize now that Atom's native code-folding feature works in .org docs, so maybe it's not needed in Organized.

**Comment by MattFlower** [comment]
I miss the "cycling" feature, I didn't really think about it until you mentioned it.  I'll put something in TODO.org for it.  It's fairly low priority, but it's easy enough that it might just get picked off.

Pull requests are always welcome.  I'm going to close this for now -- as you mentioned the built-in folding works.  This is a feature rather than an issue.
