### ISSUE TITLE
File format change?

### ISSUE THREAD

**Issue by alphapapa** [MattFlower/organized#40]
Hi,

I'm just curious, why did you decide to change the Org file format, e.g. with todo keywords and source blocks?  It doesn't seem like a good idea to make incompatible changes but keep the file extension the same.

**Comment by MattFlower** [comment]
The choice was always to support a superset of the functionality of org mode.  While I could have created a new extension, I still wanted to be able to open my existing org mode files and used the new features I was writing.

For a long time I always used brackets with my TODOs and when I intially wrote organized I went with it because, you know, I wrote this to scratch a personal itch.  There is a setting to turn off brackets around todos in the settings as now I've stopped doing that.  

In terms of source code blocks, both styles are supported in organized.  If you use the old style of course your code will work org-mode, should you decide to use it instead.  I probably should put in a setting for the toolbar.
