### ISSUE TITLE
Incorrect behavior for an empty star line

### ISSUE THREAD

**Issue by jkamenik** [MattFlower/organized#8]
In testing #6 I found that a line with a single star without following whitespace acts on the previous line; if there is more then one line.

Source (`[|]` marks the cursor).

```
* This
*[|]
```

Hit tab

```
  * This
*[|]
```

The same goes for Un-indent.

**Comment by MattFlower** [comment]
Thanks for the bug reports!

This sounds pretty reasonable to me.  Three questions:

1. I would assume your proposal would only apply if there wasn't any non-whitespace characters afterwards.  For example:
    ```
      * This
      *[|]That
    ```
Would not indent because of the "That" without whitespace after second bullet.

2. If you had this setup before you indented:
    ```
      * This
      *[|]
    ```
And you were to indent, would you expect no space added after the star:
    ```
      * This
        *[|]
    ```
or a space automatically added
    ```
      * This
        * [|]
    ```
?

3. I'm genuinely curious how you got into this position.  Is it something you see infrequently because you happened to delete a space?  I ask in case there some set of test cases I'm not thinking of.

**Comment by MattFlower** [comment]
This should be fixed at this point, with me making the assumption that in case 2 that a space shouldn't be added.  @jkamenik I am still interested in your opinion about all three though.

**Comment by jkamenik** [comment]
To answer your questions.

1. If my cursor is anywhere on a given line "tab" should re-indent the entire line.  This is not a common behavior, but one I really miss from emacs.

2. I like the last option where the extra whitespace is added after the star

3. I was having trouble understanding what the unit tests were doing so instead I created a file with bunch of the cases I was interested in.  After I got all the unit tests working I would go to the file and start manually testing.  My editor config removes ending whitespace; so on save `*[space]` was reduced to `*`.  The next time I ran my manual tests I saw the issue.
